### ISSUE TITLE
SetPassphraseCallback(Null, Null) leads to error

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/archive.mod#2]
Current passphraseCallback does not check validity of the passphraseCallback property
So when setting the passphrase callback to Null it leads to an error.
```
archive.SetPassphraseCallback(Null, Null)
```

```
Private
	Function _passphraseCallback:Byte Ptr(archive:TReadArchive) { nomangle }
		Local pass:String = archive.passphraseCallback(archive, archive.passphraseCallbackData)
		Local length:Size_T = 1024
		Return pass.ToUTF8StringBuffer(archive.pw, length)
	End Function
```

```
Private
	Function _passphraseCallback:Byte Ptr(archive:TReadArchive) { nomangle }
		Local pass:String
		If archive.passphraseCallback
			pass = archive.passphraseCallback(archive, archive.passphraseCallbackData)
		EndIf
		Local length:Size_T = 1024
		Return pass.ToUTF8StringBuffer(archive.pw, length)
	End Function
```

**Comment by GWRon** [comment]
Should be fixed with the latest commits.

**Comment by WGZero05** [comment]
I tried to recompile the Example_03.bmx from Zip.mod folder and It's still not working. No 'input password happened'.
It got worst. I recorded the screen while compiling it. Here the video.


https://user-images.githubusercontent.com/97401547/152537726-7872ba10-d903-4663-96c8-8905dd9115f2.mp4

**Comment by WGZero05** [comment]
Nevermind. I forgot to remove  `AES256` and change it to `ra.SetFormat(EArchiveFormat.ZIP)`. 
`AES256` is not working as encrypted. It works now! Thanks!
